version: '3.1'
services:

  file-server:
    image: "file-server:v0.1"
    ports:
    - 8000:8000
    env_file:
    - ./file-env
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
    - ./db-env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
