# Generated by Django 4.0.2 on 2022-02-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qcow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('qcow', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
