# Generated by Django 4.0.2 on 2022-02-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_qcow_delete_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcow',
            old_name='qcow',
            new_name='file',
        ),
    ]
